{% set name = "dgpsi" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dgpsi-{{ version }}.tar.gz
  sha256: 31c34f66b0117e59be13ae4449244eeb6f496a6ab1b2baff604d382e4f4fb9ad

build:
  number: 0
  skip: true   # [py>=40 or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - cython >=0.29.30
    - dill >=0.3.2
    - jupyter >=1.0.0
    - matplotlib-base >=3.2.1
    - numba >=0.51.2
    - numpy >=1.18.2
    - pathos >=0.2.9
    - psutil >=5.8.0
    - pybind11 >=2.10.0
    - python
    - pythran >=0.11.0
    - scikit-build >=0.15.0
    - scikit-learn >=0.22.0
    - scipy >=1.4.1
    - tabulate >=0.8.7
    - tqdm >=4.50.2

test:
  imports:
    - dgpsi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mingdeyu/DGP
  summary: A Python package for deep and linked Gaussian process emulations
  license: MIT
  license_file: LICENSE
  doc_url: https://dgpsi.readthedocs.io/
  dev_url: https://github.com/mingdeyu/DGP

extra:
  recipe-maintainers:
    - mingdeyu
