{% set name = "dgpsi" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dgpsi-{{ version }}.tar.gz
  sha256: ff242d5a273739294e5dc6380b3733b2f5e8bfa58a726cc2a0c4bf385f8909e1

build:
  number: 0
  skip: true   # [py>=311 or py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python >=3.7,<=3.10
  run:
    - cython >=0.29.30
    - dill >=0.3.2,<=0.3.5.1
    - jupyter >=1.0.0
    - matplotlib-base >=3.2.1
    - numba >=0.51.2
    - numpy >=1.18.2
    - pathos ==0.2.9
    - multiprocess ==0.70.13
    - psutil >=5.8.0
    - pybind11 >=2.10.0
    - python >=3.7,<=3.10
    - pythran >=0.11.0
    - scikit-build >=0.15.0
    - scikit-learn >=0.22.0
    - scipy >=1.4.1
    - tabulate >=0.8.7
    - tqdm >=4.50.2
    - faiss-cpu >= 1.7.4

test:
  imports:
    - dgpsi
    - faiss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mingdeyu/DGP
  summary: A Python package for deep and linked Gaussian process emulations using stochastic imputation
  license: MIT
  license_file: LICENSE
  doc_url: https://dgpsi.readthedocs.io/
  dev_url: https://github.com/mingdeyu/DGP

extra:
  recipe-maintainers:
    - mingdeyu
